iio: Add AccelerometerRaw support for direct access of sensor values
hadess/iio-sensor-proxy pull request #193
Opened 2017-10-15 16:25 UTC by janbrummer

Fixes: https://github.com/hadess/iio-sensor-proxy/issues/21

2017-10-15 17:57 UTC, hadess requested changes

2017-10-15 17:57 UTC, hadess commented on src/iio-sensor-proxy.c
> +				       g_variant_new ("(iiix)", data->previous_accel_x, data->previous_accel_y, data->previous_accel_z, g_get_real_time()));
That's not correct. The time needs to come from the drivers. Doing this for the evdev/input drivers is pretty straight forward, but I couldn't figure out how to do it for IIO. See #31.

2017-10-15 17:57 UTC, hadess commented on src/iio-sensor-proxy.c
> +		g_variant_builder_add (&props_builder, "{sv}", "AccelerometerRaw",
We really don't want to be sending this as properties, as the client side would be racy. This should be sent out as a signal, so that the data is available as a single event, and we don't miss any of those events.

2017-10-15 17:57 UTC, hadess commented on src/iio-sensor-proxy.c
> +		g_variant_builder_add (&props_builder, "{sv}", "AccelerometerRaw",
Don't forget to also update the documentation in `net.hadess.SensorProxy.xml`!

2017-10-15 19:07 UTC, janbrummer commented on src/iio-sensor-proxy.c
> +		g_variant_builder_add (&props_builder, "{sv}", "AccelerometerRaw",
Ok, i'll change it, but for the record: Why is it different to e.g. LightLevel or AcclerometerOrientation?

2017-10-15 19:09 UTC, janbrummer commented on src/iio-sensor-proxy.c
> +				       g_variant_new ("(iiix)", data->previous_accel_x, data->previous_accel_y, data->previous_accel_z, g_get_real_time()));
I'll have a look, but in case i cannot find a solution yet, should it be omitted?

2017-10-16 01:04 UTC, hadess commented on src/iio-sensor-proxy.c
> +		g_variant_builder_add (&props_builder, "{sv}", "AccelerometerRaw",
Light level and orientation don't change as often, and it's not super important if we miss a property change.

Sending the accelerometer data probably needs to happen at a much higher rate (we read every 700 msec, we probably want that position to be reported every 16msec if we want it to be usable as a controller).

2017-10-16 01:05 UTC, hadess commented on src/iio-sensor-proxy.c
> +				       g_variant_new ("(iiix)", data->previous_accel_x, data->previous_accel_y, data->previous_accel_z, g_get_real_time()));
Sure, we can send out g_get_real_time() output, as we have another issue to handle this.

2017-10-18 23:41 UTC, hadess reviewed
We still need a way to start/stop the raw data reporting, something similar to the Claim/Release calls, but for the accelerometer raw data.

2017-10-18 23:41 UTC, hadess commented on src/iio-sensor-proxy.c
> +	accel = g_variant_new ("(iiix)", data->previous_accel_x, data->previous_accel_y, data->previous_accel_z, g_get_real_time());
A linefeed after each of the arguments, like the dbus call just below, would be nice.

2017-10-18 23:41 UTC, hadess commented on src/iio-sensor-proxy.c
> +	PROP_ACCELEROMETER_RAW          = 1 << 6,
Can you please squash this patch with the one following it in your branch?

2017-10-20 22:05 UTC, janbrummer commented
I've squashed and updated the patch. It now contains Claim/ReleaseAccelerometerRaw methods and is capable of chaning poll intervall for buffered accel between NORMAL (700) and HIGH (16).

2017-10-30 05:04 UTC, hadess requested changes
Still a lot of structural problems, but the end is in sight :)

2017-10-30 05:04 UTC, hadess commented on src/net.hadess.SensorProxy.xml
> +       readings are not required anymore. For example, an application that monitors
That's a bad example...

2017-10-30 05:04 UTC, hadess commented on src/monitor-sensor.c
> +	/*g_dbus_proxy_call_sync (iio_proxy,
Why?

There should probably be a new option to listen to the computed and to the raw accelerometer data (maybe booleans so we can launch monitor-sensor multiple times, and check whether unwanted signals get sent to it?)

2017-10-30 05:04 UTC, hadess commented on src/drv-iio-buffer-accel.c
> +iio_buffer_accel_set_poll_interval (DriverPollInterval interval)
This should probably be in the core, shared between implementations.

2017-10-30 05:04 UTC, hadess commented on src/iio-sensor-proxy.c
> +				       NULL,
We already track clients, and we'll need to start using the second paramater of `g_dbus_connection_emit_signal()` to only send this signal to the D-Bus clients that are interested in it, for efficiency reasons (no need to wake a client listening to light sensor changes with an accelerometer update), and for security reasons (the raw accelerometer information should only go to the client that requested it, not all of them).

This however poses a problem as the driver types don't allow for 2 different types of clients when raw accelerometer, or computed accelerometer data is requested).

2017-10-30 05:04 UTC, hadess commented on src/iio-sensor-proxy.c
> +				driver_set_poll_interval (DRIVER_FOR_TYPE(driver_type), DRIVER_POLL_INTERVAL_HIGH);
The way you've implemented this means that if a client requests a computed acceleremeter reading after a client requested raw, we'll switch the polling back. We should instead be able to see whether there are still raw clients, and if not, switch back to NORMAL.

2017-10-30 05:04 UTC, hadess commented on src/monitor-sensor.c
> +	if (g_strcmp0(signal_name, "AccelerometerRawUpdated"))
Spaces before parenthesis please. And you should add `!= 0` here. Maybe use `g_str_equal()` to make this more readable?

2020-01-09 15:37 UTC, hadess commented
Moved to https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/merge_requests/193

2020-01-09 15:37 UTC, closed without merging