WIP Proximity sensor suppot
hadess/iio-sensor-proxy pull request #291
Opened 2019-12-20 17:12 UTC by agx

This adds proximity sensor support. The proximity of the vcnl4000 is single raw value. I'm marking as WIP since i'm not sure if this should be a different interface like compass or just go into the main interface?

2019-12-22 19:26 UTC, agx commented
while working on #292 i noticed that drivers like the vcnl4000 that have both proximity and als currently have the issue that the same device can't have multiple IIO_SENSOR_PROXY_TYPE types. What would be the way forward here, making IIO_SENSOR_PROXY_TYPE a comma seperated list?

2020-01-06 16:46 UTC, hadess commented
> while working on #292 i noticed that drivers like the vcnl4000 that have both proximity and als currently have the issue that the same device can't have multiple IIO_SENSOR_PROXY_TYPE types. What would be the way forward here, making IIO_SENSOR_PROXY_TYPE a comma seperated list?

That sounds good, yes.

As for whether the interface should be separate, or simply another one like light, I think it depends on whether we consider it a potential security risk. Pointers to what Android, Windows or iOS consider it to be would be useful in making a decision.

2020-01-08 10:41 UTC, agx commented
> As for whether the interface should be separate, or simply another one like light, I think it depends on whether we consider it a potential security risk. Pointers to what Android, Windows or iOS consider it to be would be useful in making a decision.

android does not need extra permissions for the proximity sensor, there's no mention of permissions at https://developer.android.com/guide/topics/sensors/sensors_overview (see also https://stackoverflow.com/questions/20497087/manifest-xml-when-using-sensors), same seems to be true for iOS (https://developer.apple.com/documentation/uikit/uidevice/1620017-proximitymonitoringenabled?language=objc , https://developer.apple.com/documentation/uikit/uidevice)
so i'll drop the extra dbus interface. I'll also split the support for different sensor types types into an extra series since these are independent things.

2020-01-08 11:30 UTC, hadess requested changes

2020-01-08 11:30 UTC, hadess commented on src/drivers.h
> +	int prox;
Do you want to export a simple "there's something close" boolean? Or the raw values from the sensor, or the values converted to meters, as the docs says we can?

From the docs:
```
What:           /sys/.../iio:deviceX/in_proximity_raw
What:           /sys/.../iio:deviceX/in_proximity_input
What:           /sys/.../iio:deviceX/in_proximityY_raw
KernelVersion:  3.4
Contact:        linux-iio@vger.kernel.org
Description:
                Proximity measurement indicating that some 
                object is near the sensor, usually by observing
                reflectivity of infrared or ultrasound emitted.
                Often these sensors are unit less and as such conversion
                to SI units is not possible. Higher proximity measurements
                indicate closer objects, and vice versa. Units after
                application of scale and offset are meters.
```

I think I would prefer if the D-Bus interface only ever sent a boolean. You'd either need to have a non-raw IIO proximity sensor (eg. it has scale and offset) or have those approximated by a udev property. Finally, we'd need to make a decision on what is considered close (maybe a couple of centimeters?) and make sure not to fluctuate too much when the position changes from ever so slightly above the threshold.

If your testing device has scale and offset, I'm fine with not having support for devices without those.

2020-01-08 11:30 UTC, hadess commented on src/drv-iio-poll-proximity.c
> +sysfs_get_int (GUdevDevice *dev,
`g_udev_device_get_sysfs_attr_as_int()`?

2020-01-08 11:30 UTC, hadess commented on src/drv-iio-poll-proximity.c
> +	if (drv_data->timeout_id) {
This is new code, so `g_clear_handle_id()` (if you want to also make that change in other drivers, and bump the glib version required to 2.56, that'd be great)

2020-01-08 11:30 UTC, hadess commented on README.md
> +gdbus introspect --system --dest net.hadess.SensorProxy --object-path /net/hadess/SensorProxy/Compass
This isn't quite true, only the `geoclue` user is allowed to poke at that compass path. I'd leave that change out.

2020-01-08 11:30 UTC, hadess commented on src/net.hadess.SensorProxy.xml
> +       To start receiving proximity heading updates from the proxy, the
Copy/paste error for this whole documentation section.

2020-01-08 11:30 UTC, hadess commented on src/net.hadess.SensorProxy.xml
> +    <property name='ProximityProximity' type='i' access='read'/>
We probably want that to be a bool.

2020-01-09 15:37 UTC, hadess commented
Moved to https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/merge_requests/291

2020-01-09 15:37 UTC, closed without merging